/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ExampleInterface extends ethers.utils.Interface {
  functions: {
    "age()": FunctionFragment;
    "sumOf2Numbers(int256,int256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "age", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "sumOf2Numbers",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "age", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sumOf2Numbers",
    data: BytesLike
  ): Result;

  events: {};
}

export class Example extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ExampleInterface;

  functions: {
    age(overrides?: CallOverrides): Promise<[BigNumber]>;

    "age()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    sumOf2Numbers(
      a: BigNumberish,
      b: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "sumOf2Numbers(int256,int256)"(
      a: BigNumberish,
      b: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  age(overrides?: CallOverrides): Promise<BigNumber>;

  "age()"(overrides?: CallOverrides): Promise<BigNumber>;

  sumOf2Numbers(
    a: BigNumberish,
    b: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "sumOf2Numbers(int256,int256)"(
    a: BigNumberish,
    b: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    age(overrides?: CallOverrides): Promise<BigNumber>;

    "age()"(overrides?: CallOverrides): Promise<BigNumber>;

    sumOf2Numbers(
      a: BigNumberish,
      b: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "sumOf2Numbers(int256,int256)"(
      a: BigNumberish,
      b: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    age(overrides?: CallOverrides): Promise<BigNumber>;

    "age()"(overrides?: CallOverrides): Promise<BigNumber>;

    sumOf2Numbers(
      a: BigNumberish,
      b: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "sumOf2Numbers(int256,int256)"(
      a: BigNumberish,
      b: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    age(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "age()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    sumOf2Numbers(
      a: BigNumberish,
      b: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "sumOf2Numbers(int256,int256)"(
      a: BigNumberish,
      b: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
