/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ExampleInterface extends ethers.utils.Interface {
  functions: {
    "age()": FunctionFragment;
    "career()": FunctionFragment;
    "name()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "age", values?: undefined): string;
  encodeFunctionData(functionFragment: "career", values?: undefined): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;

  decodeFunctionResult(functionFragment: "age", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "career", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;

  events: {};
}

export class Example extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ExampleInterface;

  functions: {
    age(overrides?: CallOverrides): Promise<[BigNumber]>;

    "age()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    career(overrides?: CallOverrides): Promise<[string]>;

    "career()"(overrides?: CallOverrides): Promise<[string]>;

    name(overrides?: CallOverrides): Promise<[string]>;

    "name()"(overrides?: CallOverrides): Promise<[string]>;
  };

  age(overrides?: CallOverrides): Promise<BigNumber>;

  "age()"(overrides?: CallOverrides): Promise<BigNumber>;

  career(overrides?: CallOverrides): Promise<string>;

  "career()"(overrides?: CallOverrides): Promise<string>;

  name(overrides?: CallOverrides): Promise<string>;

  "name()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    age(overrides?: CallOverrides): Promise<BigNumber>;

    "age()"(overrides?: CallOverrides): Promise<BigNumber>;

    career(overrides?: CallOverrides): Promise<string>;

    "career()"(overrides?: CallOverrides): Promise<string>;

    name(overrides?: CallOverrides): Promise<string>;

    "name()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    age(overrides?: CallOverrides): Promise<BigNumber>;

    "age()"(overrides?: CallOverrides): Promise<BigNumber>;

    career(overrides?: CallOverrides): Promise<BigNumber>;

    "career()"(overrides?: CallOverrides): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    "name()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    age(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "age()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    career(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "career()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "name()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
