/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface HelloWorldInterface extends ethers.utils.Interface {
  functions: {
    "getGreeting()": FunctionFragment;
    "greeting()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getGreeting",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "greeting", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "getGreeting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "greeting", data: BytesLike): Result;

  events: {};
}

export class HelloWorld extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: HelloWorldInterface;

  functions: {
    getGreeting(overrides?: CallOverrides): Promise<[string]>;

    "getGreeting()"(overrides?: CallOverrides): Promise<[string]>;

    greeting(overrides?: CallOverrides): Promise<[string]>;

    "greeting()"(overrides?: CallOverrides): Promise<[string]>;
  };

  getGreeting(overrides?: CallOverrides): Promise<string>;

  "getGreeting()"(overrides?: CallOverrides): Promise<string>;

  greeting(overrides?: CallOverrides): Promise<string>;

  "greeting()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    getGreeting(overrides?: CallOverrides): Promise<string>;

    "getGreeting()"(overrides?: CallOverrides): Promise<string>;

    greeting(overrides?: CallOverrides): Promise<string>;

    "greeting()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    getGreeting(overrides?: CallOverrides): Promise<BigNumber>;

    "getGreeting()"(overrides?: CallOverrides): Promise<BigNumber>;

    greeting(overrides?: CallOverrides): Promise<BigNumber>;

    "greeting()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getGreeting(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getGreeting()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    greeting(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "greeting()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
